/* In-memory report store — Phase 2 */

import { v4 as uuidv4 } from 'uuid';

export interface ReportMeta {
  id: string;
  projectId: string;
  reportType: string;
  title: string;
  format: string;
  status: 'generating' | 'ready' | 'failed';
  createdAt: string;
}

export interface GeneratedReport {
  metadata: ReportMeta;
  content: string;
}

const reports: Map<string, GeneratedReport> = new Map();

function buildWeeklyProgressHTML(projectId: string): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Weekly Progress Report — TaktFlow AI</title>
  <style>
    body { font-family: 'Inter', Arial, sans-serif; margin: 0; padding: 40px; color: #1a1a2e; background: #fff; max-width: 900px; margin: 0 auto; }
    h1 { font-family: 'Fraunces', Georgia, serif; color: #1a1a2e; border-bottom: 3px solid #6366f1; padding-bottom: 12px; }
    h2 { color: #4338ca; margin-top: 32px; }
    .metric-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 20px 0; }
    .metric-card { background: #f5f3ff; border-radius: 12px; padding: 20px; text-align: center; }
    .metric-value { font-size: 32px; font-weight: 700; color: #4338ca; }
    .metric-label { font-size: 13px; color: #6b7280; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th { background: #4338ca; color: white; padding: 10px 14px; text-align: left; font-size: 13px; }
    td { padding: 10px 14px; border-bottom: 1px solid #e5e7eb; font-size: 14px; }
    tr:nth-child(even) { background: #f9fafb; }
    .status-badge { display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 12px; font-weight: 600; }
    .status-green { background: #d1fae5; color: #065f46; }
    .status-yellow { background: #fef3c7; color: #92400e; }
    .status-red { background: #fee2e2; color: #991b1b; }
    .section { margin-bottom: 32px; }
    .recommendation { background: #eff6ff; border-left: 4px solid #3b82f6; padding: 16px; margin: 8px 0; border-radius: 0 8px 8px 0; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; text-align: center; }
    .ppc-bar { height: 24px; border-radius: 12px; background: #e5e7eb; overflow: hidden; }
    .ppc-fill { height: 100%; border-radius: 12px; transition: width 0.3s; }
  </style>
</head>
<body>
  <h1>Weekly Progress Report</h1>
  <p style="color: #6b7280;">Project: Hotel Sapphire Istanbul &middot; Week 12 (March 23–27, 2026) &middot; Generated by TaktFlow AI</p>

  <div class="section">
    <h2>Executive Summary</h2>
    <p>Week 12 shows strong performance with PPC at 93%, exceeding the 85% target. The project remains on schedule with 67% of MEP rough-in complete. Two task failures were recorded, both attributable to material and labor issues — neither impacts the critical path.</p>
  </div>

  <div class="metric-grid">
    <div class="metric-card">
      <div class="metric-value">93%</div>
      <div class="metric-label">PPC (Percent Plan Complete)</div>
    </div>
    <div class="metric-card">
      <div class="metric-value">87</div>
      <div class="metric-label">AI Health Score</div>
    </div>
    <div class="metric-card">
      <div class="metric-value">5</div>
      <div class="metric-label">Open Constraints</div>
    </div>
    <div class="metric-card">
      <div class="metric-value">78%</div>
      <div class="metric-label">Constraint Removal Rate</div>
    </div>
  </div>

  <div class="section">
    <h2>Trade Performance</h2>
    <table>
      <thead>
        <tr><th>Trade</th><th>Committed</th><th>Completed</th><th>PPC</th><th>Status</th></tr>
      </thead>
      <tbody>
        <tr><td>Structure</td><td>4</td><td>4</td><td>100%</td><td><span class="status-badge status-green">On Track</span></td></tr>
        <tr><td>MEP Rough-in</td><td>4</td><td>4</td><td>100%</td><td><span class="status-badge status-green">On Track</span></td></tr>
        <tr><td>Drywall</td><td>4</td><td>4</td><td>100%</td><td><span class="status-badge status-green">On Track</span></td></tr>
        <tr><td>MEP Finish</td><td>4</td><td>4</td><td>100%</td><td><span class="status-badge status-green">On Track</span></td></tr>
        <tr><td>Painting</td><td>4</td><td>3</td><td>75%</td><td><span class="status-badge status-yellow">At Risk</span></td></tr>
        <tr><td>Flooring</td><td>4</td><td>4</td><td>100%</td><td><span class="status-badge status-green">On Track</span></td></tr>
        <tr><td>Final Fix</td><td>4</td><td>3</td><td>75%</td><td><span class="status-badge status-yellow">At Risk</span></td></tr>
      </tbody>
    </table>
  </div>

  <div class="section">
    <h2>Constraint Status</h2>
    <table>
      <thead>
        <tr><th>ID</th><th>Description</th><th>Category</th><th>Priority</th><th>Status</th></tr>
      </thead>
      <tbody>
        <tr><td>C-041</td><td>Steel delivery for Zone 8</td><td>Material</td><td><span class="status-badge status-red">Critical</span></td><td>Open</td></tr>
        <tr><td>C-042</td><td>MEP shop drawing revision</td><td>Design</td><td><span class="status-badge status-red">Critical</span></td><td>Open</td></tr>
        <tr><td>C-043</td><td>Zone 5 MEP inspection</td><td>Permit</td><td><span class="status-badge status-yellow">Medium</span></td><td>In Progress</td></tr>
        <tr><td>C-044</td><td>Crane schedule conflict</td><td>Equipment</td><td><span class="status-badge status-yellow">Medium</span></td><td>Open</td></tr>
        <tr><td>C-045</td><td>Staging area cleanup Zone 3</td><td>Space</td><td><span class="status-badge status-green">Low</span></td><td>Open</td></tr>
      </tbody>
    </table>
  </div>

  <div class="section">
    <h2>Variance Analysis</h2>
    <p>Two task failures recorded this week:</p>
    <table>
      <thead>
        <tr><th>Task</th><th>Trade</th><th>Zone</th><th>Category</th><th>Root Cause</th></tr>
      </thead>
      <tbody>
        <tr><td>Paint application</td><td>Painting</td><td>Zone 4</td><td>Material</td><td>Paint materials not delivered on time</td></tr>
        <tr><td>Final fix installation</td><td>Final Fix</td><td>Zone 6</td><td>Labor</td><td>2 of 6 crew members absent</td></tr>
      </tbody>
    </table>
  </div>

  <div class="section">
    <h2>Recommendations</h2>
    <div class="recommendation">
      <strong>1. Pre-order paint materials</strong> — Order paint 2 weeks ahead to prevent recurrence. Contact supplier for guaranteed delivery dates.
    </div>
    <div class="recommendation">
      <strong>2. Escalate steel delivery</strong> — C-041 impacts 3 downstream trades. Arrange direct communication with steel supplier.
    </div>
    <div class="recommendation">
      <strong>3. Backup crew arrangement</strong> — Establish standby crew agreement for Final Fix trade to handle absences.
    </div>
  </div>

  <div class="section">
    <h2>Lookahead — Next 2 Weeks</h2>
    <table>
      <thead>
        <tr><th>Week</th><th>Key Activities</th><th>Constraints to Clear</th></tr>
      </thead>
      <tbody>
        <tr><td>Week 13 (Mar 30 – Apr 3)</td><td>MEP Finish Zone 1-2, Painting Zone 5-6</td><td>C-042 (Design), C-043 (Permit)</td></tr>
        <tr><td>Week 14 (Apr 6 – Apr 10)</td><td>MEP Finish Zone 3-4, Flooring Zone 1-2</td><td>C-041 (Material)</td></tr>
      </tbody>
    </table>
  </div>

  <div class="footer">
    <p>Generated by TaktFlow AI &middot; ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} &middot; Confidential</p>
  </div>
</body>
</html>`;
}

function buildExecutiveSummaryHTML(projectId: string): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Executive Summary — TaktFlow AI</title>
  <style>
    body { font-family: 'Inter', Arial, sans-serif; margin: 0; padding: 40px; color: #1a1a2e; background: #fff; max-width: 900px; margin: 0 auto; }
    h1 { font-family: 'Fraunces', Georgia, serif; color: #1a1a2e; border-bottom: 3px solid #6366f1; padding-bottom: 12px; }
    h2 { color: #4338ca; margin-top: 32px; }
    .hero { background: linear-gradient(135deg, #4338ca 0%, #6366f1 100%); color: white; padding: 32px; border-radius: 16px; margin: 24px 0; }
    .hero h2 { color: white; margin-top: 0; }
    .hero .score { font-size: 64px; font-weight: 800; }
    .metric-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 20px 0; }
    .metric-card { background: #f5f3ff; border-radius: 12px; padding: 20px; text-align: center; }
    .metric-value { font-size: 28px; font-weight: 700; color: #4338ca; }
    .metric-label { font-size: 13px; color: #6b7280; margin-top: 4px; }
    .milestone { display: flex; align-items: center; gap: 12px; padding: 12px 0; border-bottom: 1px solid #e5e7eb; }
    .milestone-dot { width: 12px; height: 12px; border-radius: 50%; }
    .dot-green { background: #10b981; }
    .dot-yellow { background: #f59e0b; }
    .dot-gray { background: #d1d5db; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; text-align: center; }
  </style>
</head>
<body>
  <h1>Executive Summary</h1>
  <p style="color: #6b7280;">Hotel Sapphire Istanbul &middot; March 2026 &middot; Generated by TaktFlow AI</p>

  <div class="hero">
    <h2>Project Health Score</h2>
    <div class="score">87/100</div>
    <p>Project is performing above target across all key metrics. Schedule reliability has improved significantly over the past 12 weeks.</p>
  </div>

  <div class="metric-grid">
    <div class="metric-card"><div class="metric-value">93%</div><div class="metric-label">Schedule Reliability (PPC)</div></div>
    <div class="metric-card"><div class="metric-value">67%</div><div class="metric-label">Overall Progress</div></div>
    <div class="metric-card"><div class="metric-value">96%</div><div class="metric-label">Budget Utilization</div></div>
  </div>

  <h2>Milestones</h2>
  <div class="milestone"><div class="milestone-dot dot-green"></div><div><strong>Structure Complete</strong> — All 6 zones, completed March 5 (on time)</div></div>
  <div class="milestone"><div class="milestone-dot dot-yellow"></div><div><strong>MEP Rough-in Complete</strong> — Target April 10 (on track)</div></div>
  <div class="milestone"><div class="milestone-dot dot-gray"></div><div><strong>Interior Finishing Complete</strong> — Target May 22</div></div>
  <div class="milestone"><div class="milestone-dot dot-gray"></div><div><strong>Handover</strong> — Target June 15</div></div>

  <h2>Key Risks</h2>
  <p>1. <strong>Steel delivery delay</strong> — Zone 8 steel has no confirmed delivery date. Impact: potential 5-day delay to finishing trades.</p>
  <p>2. <strong>MEP subcontractor capacity</strong> — Current crew may be insufficient for April peak workload. Mitigation: pre-arrange backup crews.</p>

  <div class="footer">
    <p>Generated by TaktFlow AI &middot; ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} &middot; Confidential</p>
  </div>
</body>
</html>`;
}

function buildVarianceAnalysisHTML(projectId: string): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Variance Analysis — TaktFlow AI</title>
  <style>
    body { font-family: 'Inter', Arial, sans-serif; margin: 0; padding: 40px; color: #1a1a2e; background: #fff; max-width: 900px; margin: 0 auto; }
    h1 { font-family: 'Fraunces', Georgia, serif; border-bottom: 3px solid #6366f1; padding-bottom: 12px; }
    h2 { color: #4338ca; margin-top: 32px; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th { background: #4338ca; color: white; padding: 10px 14px; text-align: left; font-size: 13px; }
    td { padding: 10px 14px; border-bottom: 1px solid #e5e7eb; font-size: 14px; }
    .bar-container { background: #e5e7eb; height: 20px; border-radius: 10px; overflow: hidden; }
    .bar-fill { height: 100%; border-radius: 10px; }
    .insight { background: #fefce8; border-left: 4px solid #eab308; padding: 16px; margin: 12px 0; border-radius: 0 8px 8px 0; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; text-align: center; }
  </style>
</head>
<body>
  <h1>Variance Analysis Report</h1>
  <p style="color: #6b7280;">Hotel Sapphire Istanbul &middot; Weeks 1–12 &middot; Generated by TaktFlow AI</p>

  <h2>Variance Overview</h2>
  <p>Over 12 weeks, <strong>38 task failures</strong> were recorded out of 336 committed tasks (88.7% overall PPC). The improving trend (62% → 93%) indicates strong corrective actions.</p>

  <h2>Variance by Category</h2>
  <table>
    <thead><tr><th>Category</th><th>Count</th><th>Percentage</th><th>Distribution</th></tr></thead>
    <tbody>
      <tr><td>Material</td><td>13</td><td>34%</td><td><div class="bar-container"><div class="bar-fill" style="width:34%;background:#ef4444"></div></div></td></tr>
      <tr><td>Labor</td><td>9</td><td>24%</td><td><div class="bar-container"><div class="bar-fill" style="width:24%;background:#f97316"></div></div></td></tr>
      <tr><td>Design</td><td>6</td><td>16%</td><td><div class="bar-container"><div class="bar-fill" style="width:16%;background:#eab308"></div></div></td></tr>
      <tr><td>Predecessor</td><td>4</td><td>11%</td><td><div class="bar-container"><div class="bar-fill" style="width:11%;background:#3b82f6"></div></div></td></tr>
      <tr><td>Equipment</td><td>3</td><td>8%</td><td><div class="bar-container"><div class="bar-fill" style="width:8%;background:#8b5cf6"></div></div></td></tr>
      <tr><td>Space</td><td>2</td><td>5%</td><td><div class="bar-container"><div class="bar-fill" style="width:5%;background:#6b7280"></div></div></td></tr>
      <tr><td>Information</td><td>1</td><td>3%</td><td><div class="bar-container"><div class="bar-fill" style="width:3%;background:#9ca3af"></div></div></td></tr>
    </tbody>
  </table>

  <div class="insight">
    <strong>Key Insight:</strong> Material-related failures account for 34% of all variances. Most are concentrated in the Painting and MEP trades. Implementing a 2-week advance ordering policy could reduce these by 60%.
  </div>

  <h2>Variance by Trade</h2>
  <table>
    <thead><tr><th>Trade</th><th>Failures</th><th>Avg PPC</th><th>Trend</th></tr></thead>
    <tbody>
      <tr><td>Painting</td><td>8</td><td>79%</td><td>Improving ↑</td></tr>
      <tr><td>MEP Rough-in</td><td>7</td><td>82%</td><td>Stable →</td></tr>
      <tr><td>Final Fix</td><td>6</td><td>84%</td><td>Improving ↑</td></tr>
      <tr><td>Drywall</td><td>5</td><td>86%</td><td>Improving ↑</td></tr>
      <tr><td>Flooring</td><td>5</td><td>86%</td><td>Stable →</td></tr>
      <tr><td>MEP Finish</td><td>4</td><td>89%</td><td>Improving ↑</td></tr>
      <tr><td>Structure</td><td>3</td><td>92%</td><td>Stable →</td></tr>
    </tbody>
  </table>

  <h2>Recovery Recommendations</h2>
  <p>1. <strong>Material Management:</strong> Implement 2-week advance ordering for all finishing materials.</p>
  <p>2. <strong>Labor Backup:</strong> Establish standby crew agreements for trades with >20% failure rate.</p>
  <p>3. <strong>Design Coordination:</strong> Weekly RFI review meetings with architect to clear design constraints faster.</p>

  <div class="footer">
    <p>Generated by TaktFlow AI &middot; ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} &middot; Confidential</p>
  </div>
</body>
</html>`;
}

export function generateReport(projectId: string, reportType: string, title?: string, format?: string): GeneratedReport {
  const id = uuidv4();
  const reportTitle = title || `${reportType.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())} — ${new Date().toLocaleDateString()}`;

  let content: string;
  switch (reportType) {
    case 'weekly_progress':
      content = buildWeeklyProgressHTML(projectId);
      break;
    case 'executive_summary':
      content = buildExecutiveSummaryHTML(projectId);
      break;
    case 'variance_analysis':
      content = buildVarianceAnalysisHTML(projectId);
      break;
    default:
      content = buildWeeklyProgressHTML(projectId);
  }

  const report: GeneratedReport = {
    metadata: {
      id,
      projectId,
      reportType,
      title: reportTitle,
      format: format || 'html',
      status: 'ready',
      createdAt: new Date().toISOString(),
    },
    content,
  };

  reports.set(id, report);
  return report;
}

export function getReport(id: string): GeneratedReport | undefined {
  return reports.get(id);
}

export function listReports(projectId: string): ReportMeta[] {
  const result: ReportMeta[] = [];
  for (const [, report] of reports) {
    if (report.metadata.projectId === projectId) {
      result.push(report.metadata);
    }
  }
  return result.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
}

export function deleteReport(id: string): boolean {
  return reports.delete(id);
}

// Pre-generate some demo reports
generateReport('demo-project-001', 'weekly_progress', 'Weekly Progress Report — Week 11');
generateReport('demo-project-001', 'executive_summary', 'Executive Summary — February 2026');
generateReport('demo-project-001', 'variance_analysis', 'Variance Analysis — Q1 2026');
